import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../prisma.js'
import { asyncRoute } from '../http.js'
import { authenticate, managerOnly } from '../auth.js'

export const metricsRouter=Router();metricsRouter.use(authenticate)
const customBody=z.object({nome:z.string().trim().min(1),canal:z.enum(['INSTAGRAM','LINKEDIN','SITE','EMAIL']),formula:z.string(),valor:z.number(),unidade:z.enum(['PERCENT','LEADS','SESSOES','NUMERO'])})
metricsRouter.get('/custom',asyncRoute(async(_req,res)=>res.json(await prisma.customMetric.findMany({orderBy:{createdAt:'asc'}}))))
metricsRouter.post('/custom',asyncRoute(async(req,res)=>res.status(201).json(await prisma.customMetric.create({data:customBody.parse(req.body)}))))
metricsRouter.patch('/custom/:id',asyncRoute(async(req,res)=>{const body=customBody.partial().parse(req.body);res.json(await prisma.customMetric.update({where:{id:String(req.params.id)},data:{...body,...(body.valor!==undefined?{atualizadoEm:new Date()}: {})}}))}))
metricsRouter.delete('/custom/:id',asyncRoute(async(req,res)=>{await prisma.customMetric.delete({where:{id:String(req.params.id)}});res.status(204).send()}))

const dashboardPayload=async(plataforma:'INSTAGRAM'|'LINKEDIN')=>{
  const [kpis,formatos,funilStories,heatmap,distribution]=await Promise.all([prisma.dashboardKpi.findMany({where:{plataforma}}),prisma.contentFormatPerformance.findMany({where:{plataforma}}),prisma.storyFunnelStep.findMany({where:{plataforma},orderBy:{ordem:'asc'}}),prisma.activityHeatmapCell.findMany({where:{plataforma},orderBy:[{diaSemana:'asc'},{faixaHora:'asc'}]}),prisma.dashboardDistribution.findUnique({where:{plataforma}})])
  const now=Date.now();const decorated=kpis.map((kpi)=>({...kpi,idadeDias:Math.floor((now-kpi.atualizadoEm.getTime())/86400000)}));const old=decorated.filter((kpi)=>kpi.idadeDias>20)
  const today=new Date();const day=(today.getUTCDay()+6)%7;const start=new Date(Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate()-day));const end=new Date(start.getTime()+7*86400000)
  const aggregate=await prisma.post.aggregate({where:{canal:plataforma,dataPublicacao:{gte:start,lt:end}},_sum:{alcance:true}})
  return{plataforma,desatualizadas:{count:old.length,nomes:old.map((item)=>item.nome)},kpis:decorated,alcanceSemanal:aggregate._sum.alcance??0,alcanceSeguidores:distribution?{seguidores:distribution.principalPct,naoSeguidores:distribution.secundarioPct}:null,formatos,funilStories,heatmap}
}
metricsRouter.get('/dashboard',asyncRoute(async(req,res)=>{const plataforma=z.enum(['INSTAGRAM','LINKEDIN']).parse(req.query.plataforma);res.json(await dashboardPayload(plataforma))}))
metricsRouter.put('/dashboard',managerOnly,asyncRoute(async(req,res)=>{const plataforma=z.enum(['INSTAGRAM','LINKEDIN']).parse(req.query.plataforma);const body=z.object({kpis:z.array(z.object({nome:z.string(),valor:z.string(),variacaoPct:z.number().nullable().optional(),descricao:z.string().nullable().optional()})).optional(),alcanceSeguidores:z.object({seguidores:z.number().min(0).max(100),naoSeguidores:z.number().min(0).max(100)}).refine((v)=>Math.round(v.seguidores+v.naoSeguidores)===100).optional(),formatos:z.array(z.object({formato:z.enum(['REELS','CARROSSEL','POST_ESTATICO','STORIES','PDF_DOCUMENTO','TEXTO_IMAGEM','VIDEO','ARTIGO_NEWSLETTER','ENQUETE']),alcanceMedio:z.number().int().min(0).default(0),taxaEngajamento:z.number().min(0).default(0),saves:z.number().int().nullable().optional(),compartilhamentos:z.number().int().nullable().optional(),impressoes:z.number().int().nullable().optional(),ctr:z.number().nullable().optional(),taxaReacao:z.number().nullable().optional(),reposts:z.number().int().nullable().optional(),comentarios:z.number().int().nullable().optional()})).optional(),funilStories:z.array(z.object({ordem:z.number().int().positive(),percentual:z.number().min(0).max(100),espectadores:z.number().int().min(0)})).optional(),heatmap:z.array(z.object({diaSemana:z.number().int().min(0).max(6),faixaHora:z.number().int().min(0).max(23),intensidade:z.number().int().min(0).max(100)})).optional()}).parse(req.body);await prisma.$transaction(async(tx)=>{for(const kpi of body.kpis??[])await tx.dashboardKpi.upsert({where:{plataforma_nome:{plataforma,nome:kpi.nome}},create:{plataforma,...kpi,atualizadoEm:new Date()},update:{...kpi,atualizadoEm:new Date()}});if(body.alcanceSeguidores)await tx.dashboardDistribution.upsert({where:{plataforma},create:{plataforma,principalPct:body.alcanceSeguidores.seguidores,secundarioPct:body.alcanceSeguidores.naoSeguidores},update:{principalPct:body.alcanceSeguidores.seguidores,secundarioPct:body.alcanceSeguidores.naoSeguidores}});for(const row of body.formatos??[])await tx.contentFormatPerformance.upsert({where:{plataforma_formato:{plataforma,formato:row.formato}},create:{plataforma,...row},update:{...row,atualizadoEm:new Date()}});for(const row of body.funilStories??[])await tx.storyFunnelStep.upsert({where:{plataforma_ordem:{plataforma,ordem:row.ordem}},create:{plataforma,...row},update:row});for(const row of body.heatmap??[])await tx.activityHeatmapCell.upsert({where:{plataforma_diaSemana_faixaHora:{plataforma,diaSemana:row.diaSemana,faixaHora:row.faixaHora}},create:{plataforma,...row},update:row})});res.json(await dashboardPayload(plataforma))}))
metricsRouter.get('/dashboard/export',asyncRoute(async(req,res)=>{const plataforma=z.enum(['INSTAGRAM','LINKEDIN']).parse(req.query.plataforma);const formato=z.enum(['csv','pdf']).default('csv').parse(req.query.formato);const data=await dashboardPayload(plataforma);if(formato==='pdf')return res.status(501).json({error:{code:'PDF_EXPORT_NOT_CONFIGURED',message:'Use formato CSV neste ambiente'}});const lines=['Métrica,Valor,Variação,Atualizado em',...data.kpis.map((kpi)=>`"${kpi.nome}","${kpi.valor}",${kpi.variacaoPct??''},${kpi.atualizadoEm.toISOString()}`)];res.type('text/csv').attachment(`marketops-${plataforma.toLowerCase()}.csv`).send(lines.join('\n'))}))

const mqlBody=z.object({scoreMinimo:z.number().int().min(0).max(100),taxaMqlSql:z.number().min(0).max(100),mqlsEsteMes:z.number().int().min(0),tamanhoEmpresa:z.string(),cargosAlvo:z.array(z.string()),segmentos:z.array(z.string()),comportamentos:z.array(z.string())})
const serializeMql=(mql:any)=>mql?{id:mql.id,scoreMinimo:mql.scoreMinimo,taxaMqlSql:mql.taxaMqlSql,mqlsEsteMes:mql.mqlsEsteMes,tamanhoEmpresa:mql.tamanhoEmpresa,cargosAlvo:mql.cargosAlvo.map((x:any)=>x.nome),segmentos:mql.segmentos.map((x:any)=>x.nome),comportamentos:mql.comportamentos.map((x:any)=>x.descricao)}:{scoreMinimo:65,taxaMqlSql:0,mqlsEsteMes:0,tamanhoEmpresa:'',cargosAlvo:[],segmentos:[],comportamentos:[]}
const mqlInclude={cargosAlvo:true,segmentos:true,comportamentos:true} as const
metricsRouter.get('/mql',asyncRoute(async(_req,res)=>res.json(serializeMql(await prisma.mqlDefinition.findFirst({include:mqlInclude})))))
metricsRouter.put('/mql',managerOnly,asyncRoute(async(req,res)=>{const body=mqlBody.parse(req.body);const current=await prisma.mqlDefinition.findFirst();const row=await prisma.$transaction(async(tx)=>{if(current){await Promise.all([tx.mqlTargetRole.deleteMany({where:{mqlId:current.id}}),tx.mqlSegment.deleteMany({where:{mqlId:current.id}}),tx.mqlBehavior.deleteMany({where:{mqlId:current.id}})]);return tx.mqlDefinition.update({where:{id:current.id},data:{scoreMinimo:body.scoreMinimo,taxaMqlSql:body.taxaMqlSql,mqlsEsteMes:body.mqlsEsteMes,tamanhoEmpresa:body.tamanhoEmpresa,cargosAlvo:{create:body.cargosAlvo.map((nome)=>({nome}))},segmentos:{create:body.segmentos.map((nome)=>({nome}))},comportamentos:{create:body.comportamentos.map((descricao)=>({descricao}))}},include:mqlInclude})}return tx.mqlDefinition.create({data:{scoreMinimo:body.scoreMinimo,taxaMqlSql:body.taxaMqlSql,mqlsEsteMes:body.mqlsEsteMes,tamanhoEmpresa:body.tamanhoEmpresa,cargosAlvo:{create:body.cargosAlvo.map((nome)=>({nome}))},segmentos:{create:body.segmentos.map((nome)=>({nome}))},comportamentos:{create:body.comportamentos.map((descricao)=>({descricao}))}},include:mqlInclude})});res.json(serializeMql(row))}))
